### ISSUE TITLE
cannot upload file to kerberos-enabled hdfs

### ISSUE THREAD

**Issue by senkin13** [civitaspo/embulk-output-hdfs#17]
when I type this command: embulk run mydata/config.yml,the error below came out,can this plugin use kerberos authentication? 

org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]

**Comment by civitaspo** [comment]
Could you show me the content of `mydata/config.yml` ?
I have not verified kerberos authentication (
I do not have any Hadoop that can use Kerberos authentication.) so I do not know whether it will work.
Give me a pull request which make it available if you can!

**Comment by senkin13** [comment]
in:
  type: file
  path_prefix: ./mydata/csv/
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out:
  type: hdfs
  config_files: [/etc/hadoop/conf/core-site.xml, /etc/hadoop/conf/hdfs-site.xml]
  config: {fs.defaultFS: 'hdfs://nameservice1:8020', fs.hdfs.impl: org.apache.hadoop.hdfs.DistributedFileSystem,
    fs.file.impl: org.apache.hadoop.fs.LocalFileSystem}
  path_prefix: /etl/input/
  file_ext: txt
  overwrite: true
  formatter: {type: csv, encoding: UTF-8}

Do you have any idea?

**Comment by civitaspo** [comment]
hmm, I do not have any idea. I think there is something wrong in your files `/etc/hadoop/conf/core-site.xml`, `/etc/hadoop/conf/hdfs-site.xml`.

**Comment by senkin13** [comment]
Thank you,I am not java developer,maybe in the future you can add kerberos authentication.
hope this will help

http://www.ibm.com/support/knowledgecenter/en/SSPT3X_3.0.0/com.ibm.swg.im.infosphere.biginsights.admin.doc/doc/kerberos_mapreduce.html

**Comment by Jonathan-mura** [comment]
I had the same problem in my environment.

```
in:
  type: mysql
  host: 10.26.xxx.xxx
  user: hoge
  password: foo
  database: embulk_test_db
  table: test_table 
  select: "*"
out:
  type: hdfs
  config_files: 
    - /home/admin/hadoop-conf/core-site.xml
    - /home/admin/hadoop-conf/hdfs-site.xml
  config:
    hadoop.security.authentication: 'kerberos'
    hadoop.security.authorization: 'true'
  path_prefix: '/user/hoge/embulk_test_%Y-%m-%d'
  file_ext: 'txt'
  #mode: replace
  formatter:
    type: csv
    encoding: UTF-8
```

`org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]`

So I looked at this(http://www.ibm.com/support/knowledgecenter/en/SSPT3X_3.0.0/com.ibm.swg.im.infosphere.biginsights.admin.doc/doc/kerberos_mapreduce.html) document and added.

https://github.com/civitaspo/embulk-output-hdfs/blob/master/src/main/java/org/embulk/output/hdfs/client/HdfsClient.java#L27-L31
```
    public static HdfsClient build(HdfsFileOutputPlugin.PluginTask task)
    {
        Configuration conf = buildConfiguration(task.getConfigFiles(), task.getConfig());

        UserGroupInformation.setConfiguration(conf);   // add

        return new HdfsClient(conf, task.getDoas());
    }

```

↓error message

```
org.embulk.exec.PartialExecutionException: java.lang.IllegalArgumentException: Invalid rule: kerberos
Caused by: java.lang.IllegalArgumentException: Invalid rule: kerberos
at org.apache.hadoop.security.authentication.util.KerberosName.parseRules(KerberosName.java:331)
at org.apache.hadoop.security.authentication.util.KerberosName.setRules(KerberosName.java:397)
at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:75)
at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:263)
at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:299)
at org.embulk.output.hdfs.client.HdfsClient.build(HdfsClient.java:43)

```

Would you help me?
Many people are in trouble with this problem, so everyone is happy to solve it.

**Comment by civitaspo** [comment]
Thank you for the comment @Jonathan-mura. I will fix it this weekend and publish a pre-release of the next version. But, I do not have any kerberos enabled hadoop cluster, so could you verify the pre-release?  Or please give a pull-request.

**Comment by Jonathan-mura** [comment]
Thank you very much:pray:
I check it in my environment and try it.

**Comment by civitaspo** [comment]
@Jonathan-mura plz try this https://rubygems.org/gems/embulk-output-hdfs/versions/0.4.0.pre

**Comment by Jonathan-mura** [comment]
@civitaspo 
Thank you for the pre-release.

I tried with a modified version.
```
$ embulk gem list | grep embulk-output-hdfs
embulk-output-hdfs (0.4.0.pre)
```

```
$ embulk run output_hdfs.yml 
2019-12-09 15:06:07.015 +0900: Embulk v0.9.19
2019-12-09 15:06:07.820 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2019-12-09 15:06:11.058 +0900 [INFO] (main): Gem's home and path are set by default: "/home/hpadmin/.embulk/lib/gems"
2019-12-09 15:06:12.216 +0900 [INFO] (main): Started Embulk v0.9.19
2019-12-09 15:06:12.316 +0900 [INFO] (0001:transaction): Loaded plugin embulk-input-mysql (0.10.1)
2019-12-09 15:06:12.404 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-hdfs (0.4.4.pre)
2019-12-09 15:06:12.453 +0900 [INFO] (0001:transaction): JDBC Driver = /home/hpadmin/.embulk/lib/gems/gems/embulk-input-mysql-0.10.1/default_jdbc_driver/mysql-connector-java-5.1.44.jar
2019-12-09 15:06:12.461 +0900 [INFO] (0001:transaction): Fetch size is 10000. Using server-side prepared statement.
2019-12-09 15:06:12.462 +0900 [INFO] (0001:transaction): Connecting to jdbc:mysql://10.26.157.212:3306/embulk_test_db options {useCompression=true, socketTimeout=1800000, useSSL=false, user=hoge, useLegacyDatetimeCode=false, tcpKeepAlive=true, useCursorFetch=true, connectTimeout=300000, password=***, zeroDateTimeBehavior=convertToNull}
2019-12-09 15:06:12.804 +0900 [INFO] (0001:transaction): Using JDBC Driver mysql-connector-java-5.1.44 ( Revision: b3cda4f864902ffdde495b9df93937c3e20009be )
2019-12-09 15:06:12.805 +0900 [WARN] (0001:transaction): embulk-input-mysql 0.9.0 upgraded the bundled MySQL Connector/J version from 5.1.34 to 5.1.44 .
2019-12-09 15:06:12.805 +0900 [WARN] (0001:transaction): And set useLegacyDatetimeCode=false by default in order to get correct datetime value when the server timezone and the client timezone are different.
2019-12-09 15:06:12.805 +0900 [WARN] (0001:transaction): Set useLegacyDatetimeCode=true if you need to get datetime value same as older embulk-input-mysql.
2019-12-09 15:06:12.879 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=4 / output tasks 2 = input tasks 1 * 2
2019-12-09 15:06:12.937 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2019-12-09 15:06:13.314 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
org.embulk.exec.PartialExecutionException: java.lang.IllegalArgumentException: Invalid rule: kerberos
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(Exec.java:22)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:205)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:433)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
	at org.embulk.cli.Main.main(Main.java:64)
Caused by: java.lang.IllegalArgumentException: Invalid rule: kerberos
	at org.apache.hadoop.security.authentication.util.KerberosName.parseRules(KerberosName.java:343)
	at org.apache.hadoop.security.authentication.util.KerberosName.setRules(KerberosName.java:410)
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:75)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:318)
	at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:364)
	at org.embulk.output.hdfs.client.HdfsClient.buildConfiguration(HdfsClient.java:51)
	at org.embulk.output.hdfs.client.HdfsClient.build(HdfsClient.java:30)
	at org.embulk.output.hdfs.HdfsFileOutput.<init>(HdfsFileOutput.java:39)
	at org.embulk.output.hdfs.transaction.AbstractTx.newOutput(AbstractTx.java:51)
	at org.embulk.output.hdfs.transaction.AbortIfExistTx.newOutput(AbortIfExistTx.java:3)
	at org.embulk.output.hdfs.HdfsFileOutputPlugin.open(HdfsFileOutputPlugin.java:135)
	at org.embulk.spi.FileOutputRunner.open(FileOutputRunner.java:120)
	at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.openOutputs(LocalExecutorPlugin.java:402)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:256)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

error_message
`org.embulk.exec.PartialExecutionException: java.lang.IllegalArgumentException: Invalid rule: kerberos`

This problem occurred even with the modified version.
Maybe this is just my environment.

hmm, 
I will try more around kerberos authentication in my environment.

**Comment by civitaspo** [comment]
Thanks, I'm waiting for your investigation. Please let me know how to implement kerberos authentication correctly.

**Comment by Jonathan-mura** [comment]
@civitaspo 

It worked in my environment.
I'm sorry. I forgot that my hadoop environment uses cloudera-hadoop.

fix build.gradle
```
repositories {
    mavenCentral()
    jcenter()
    maven {
        url "https://repository.cloudera.com/artifactory/cloudera-repos/" // add
    }
}

dependencies {
    compile group: 'org.apache.hadoop', name: 'hadoop-client', version: '3.0.0-cdh6.1.1' // add
}
```

output_hdfs.yml
```
in:
  type: mysql
  host: 10.26.xxx.xxx
  user: hoge
  password: foo
  database: embulk_test_db
  table: test_table 
  select: "*"
out:
  type: hdfs
  config:
    fs.defaultFS: 'webhdfs://my_hadoop_host'
    fs.webhdfs.impl: 'org.apache.hadoop.hdfs.web.WebHdfsFileSystem'
    hadoop.security.authentication: 'kerberos'
  path_prefix: '/user/hoge/embulk_out_hdfs_test'
  file_ext: 'txt'
  formatter:
    type: csv
    encoding: UTF-8
```


it works!
```
$ embulk run output_hdfs.yml
...
2019-12-10 17:27:35.016 +0900 [INFO] (embulk-output-executor-0): Uploading '/user/hoge/embulk_out_hdfs_test001.00.txt'
2019-12-10 17:27:35.036 +0900 [INFO] (embulk-output-executor-1): Uploading '/user/hoge/embulk_out_hdfs_test000.00.txt'
2019-12-10 17:27:35.090 +0900 [INFO] (0014:task-0000): Fetched 4,000 rows.
2019-12-10 17:27:35.122 +0900 [INFO] (0014:task-0000): Fetched 8,000 rows.
2019-12-10 17:27:35.282 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2019-12-10 17:27:35.290 +0900 [INFO] (main): Committed.
2019-12-10 17:27:35.290 +0900 [INFO] (main): Next config diff: {"in":{},"out":{}}
```

Probably it will work with v0.4.0-pre if it is normal hadoop.
My problem has been solved.
Thank you for your help!!
